import google.generativeai as genai
import requests
import base64
import os
import json
from dotenv import load_dotenv

load_dotenv()

genai.configure(api_key=os.getenv("GEMINI_API_KEY"))
model = genai.GenerativeModel("gemini-2.5-flash-lite")


def analyze_text(text):
    prompt = f"""You are an expert AI content detector. Analyze the following text and determine if it was written by a human or generated by an AI.

Respond ONLY in this exact JSON format, nothing else, no extra text:
{{
  "verdict": "AI-Generated" or "Human-Written" or "Mixed/Uncertain",
  "confidence": a number from 0 to 100,
  "reasoning": "2-3 sentences explaining your verdict",
  "signals": ["signal 1", "signal 2", "signal 3"]
}}

Text to analyze:
\"\"\"{text}\"\"\"
"""
    response = model.generate_content(prompt)
    raw = response.text.strip()
    raw = raw.replace("```json", "").replace("```", "").strip()
    return json.loads(raw)


def analyze_image(image_data, media_type):
    prompt = """You are an expert AI image detector. Analyze this image and determine if it was created by an AI generator or by a human.

Respond ONLY in this exact JSON format, nothing else:
{
  "verdict": "AI-Generated" or "Human-Created" or "Mixed/Uncertain",
  "confidence": a number from 0 to 100,
  "reasoning": "2-3 sentences explaining your verdict",
  "signals": ["signal 1", "signal 2", "signal 3"]
}"""

    image_bytes = base64.b64decode(image_data)
    image_part = {"mime_type": media_type, "data": image_bytes}
    response = model.generate_content([prompt, image_part])
    raw = response.text.strip()
    raw = raw.replace("```json", "").replace("```", "").strip()
    return json.loads(raw)